name: Run Dollar Bot
on:
  push:
  schedule:
    - cron: '*/10 * * * *' # يشتغل كل 10 دقائق
  workflow_dispatch:
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with: {python-version: '3.9'}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python dollar_bot.py
 
 
